### ISSUE TITLE
Resume link does not work

### ISSUE THREAD

**Issue by Kyle-Verhoog** [alxch-/alex-perso#1]
<img width="641" alt="screen shot 2018-08-28 at 6 33 49 pm" src="https://user-images.githubusercontent.com/6321485/44754738-1d498d80-aaf1-11e8-8909-6fc5072a339d.png">

**Comment by alxch-** [comment]
Hi Kyle! Thank you for reporting this sneaky dead link.

**Comment by Kyle-Verhoog** [comment]
I can help you write your resume if you like, it does not appear to be present in https://github.com/alxch-/alex-perso/tree/master/content.

**Comment by Kyle-Verhoog** [comment]
@alxch- any progress? I really need this feature.

**Comment by alxch-** [comment]
Hi Kyle,

This has been addressed now.
